trigger:
  branches:
    include:
      - main

stages:
  - stage: windows_2022
    displayName: 'windows-2022'
    dependsOn: [ ]
    pool:
      vmImage: 'windows-2022'
    jobs:
      - job: CreatePackage
        displayName: 'CreatePackage'
        dependsOn: [ ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './.nuke/build.cmd CreateBundle CreateInstaller'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: CWO_App
              pathtoPublish: 'output'